# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-24 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200722_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_ck',
            field=models.TextField(blank=True, verbose_name='正文'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_md',
            field=models.TextField(blank=True, verbose_name='正文'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=False, verbose_name='markdown语法'),
        ),
    ]
