# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userToken',
            field=models.CharField(max_length=200),
        ),
    ]