# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-06 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_user_cleanstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20)),
                ('blogid', models.CharField(max_length=10)),
                ('isDelete', models.BooleanField(default=False)),
                ('noRepeat', models.CharField(default=1, max_length=30)),
            ],
        ),
    ]
