# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201015_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(blank=True, max_length=128, verbose_name='作者'),
        ),
    ]
