# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
