# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200719_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=0, verbose_name='状态'),
        ),
    ]
