# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-03 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200722_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
